name: Build UI
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: AlertToCareUI/AlertToCareUI.sln    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        
    - name: Build with dotnet
      run: dotnet build AlertToCareUI/AlertToCareUI.sln
